### PR TITLE
Changed condition governing the generation of the Skills button to also include this button for guests

### PR DESCRIPTION
**Pull request by nickweedon**

### CODE REVIEW

**Comment by nickweedon** [comment]
I often find that I will want to look through all the stats of guests when looking to recruit them. I was happy it turned out to be a simple 'one liner' to do this.
I tested the change and it seems to work as expected.
Love your mod btw :)

**Comment by nickweedon** [comment]
Added one more change to also recognize guests as 'Equipment bearers'. Primarily i wanted to see the guests 'traits' in this case.

**Comment by nickweedon** [comment]
FYI, have tested against vanilla 1.4 (including all DLC) with any other mods and have also tested in my 'real' game that includes hundreds of mods and most notably the 'hospitality' mod.
Appears to work as expected in all cases.

**Comment by Mehni** [comment]
Thank you for your addition! I'm a bit tight on time lately so a steam release will come a bit later.

It's good to hear that Numbers is manageable - that was a big goal when rewriting it all that time ago and I'm glad it has paid off.

**Pull request merged**
